#!/usr/bin/env python3
"""Mirror canonical agent skills into platform-specific directories."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from "
GENERATED_SUFFIX = ". DO NOT EDIT. -->"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def generated_content(source_rel: str, source_text: str) -> str:
    return f"{GENERATED_PREFIX}{source_rel}{GENERATED_SUFFIX}\n\n{source_text}"


def canonical_skills(root: Path) -> dict[str, Path]:
    src_root = root / ".ai" / "skills-src"
    skills: dict[str, Path] = {}
    if not src_root.exists():
        return skills
    for skill_file in sorted(src_root.glob("*/SKILL.md")):
        skill_name = skill_file.parent.name
        skills[skill_name] = skill_file
    return skills


def is_generated(text: str) -> bool:
    return text.startswith(GENERATED_PREFIX)


def sync(check: bool = False) -> int:
    root = repo_root()
    skills = canonical_skills(root)
    destinations = [root / ".agents" / "skills", root / ".claude" / "skills"]
    failures: list[str] = []

    for dest_root in destinations:
        dest_root.mkdir(parents=True, exist_ok=True)

        for name, source in skills.items():
            source_rel = source.relative_to(root).as_posix()
            expected = generated_content(source_rel, source.read_text(encoding="utf-8"))
            dest = dest_root / name / "SKILL.md"

            if check:
                if not dest.exists():
                    failures.append(f"missing generated skill: {dest.relative_to(root)}")
                    continue
                actual = dest.read_text(encoding="utf-8")
                if actual != expected:
                    failures.append(f"generated skill drift: {dest.relative_to(root)}")
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(expected, encoding="utf-8", newline="\n")

        for existing in sorted(dest_root.glob("*/SKILL.md")):
            if existing.parent.name in skills:
                continue
            text = existing.read_text(encoding="utf-8", errors="replace")
            if is_generated(text):
                if check:
                    failures.append(f"stale generated skill: {existing.relative_to(root)}")
                else:
                    shutil.rmtree(existing.parent)
            else:
                failures.append(f"non-generated skill not managed by sync: {existing.relative_to(root)}")

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        return 1

    if check:
        print("agent skill sync check passed")
    else:
        print("agent skill sync complete")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
