#!/usr/bin/env python3
"""Validate shared AI agent configuration without third-party packages."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    tomllib = None  # type: ignore[assignment]

GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from "
GENERATED_SUFFIX = ". DO NOT EDIT. -->"
NAME_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
SECRET_VALUE_RE = re.compile(
    r"(?i)(api[_-]?key|secret|token|password|private[_-]?key)\s*[:=]\s*['\"]?[A-Za-z0-9_./+=-]{16,}"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def required_paths() -> list[str]:
    return [
        "AGENTS.md",
        "CLAUDE.md",
        "AI_AGENT_TEAM_GUIDE.md",
        ".ai/README.md",
        ".ai/PROMPTS.md",
        ".ai/manifest.yaml",
        ".ai/references.md",
        ".ai/core/mission.md",
        ".ai/core/instruction-precedence.md",
        ".ai/core/engineering-principles.md",
        ".ai/core/required-workflow.md",
        ".ai/core/quality-gates.md",
        ".ai/core/code-quality-intelligence.md",
        ".ai/core/memory-policy.md",
        ".ai/core/risk-model.md",
        ".ai/core/definition-of-done.md",
        ".ai/core/output-contract.md",
        ".ai/context/architecture.md",
        ".ai/context/glossary.md",
        ".ai/context/repository-map.md",
        ".ai/context/build-test-commands.md",
        ".ai/context/ownership.md",
        ".ai/context/agent-roles.md",
        ".ai/rules/engineering.md",
        ".ai/rules/security.md",
        ".ai/rules/testing.md",
        ".ai/rules/api-design.md",
        ".ai/rules/database.md",
        ".ai/rules/observability.md",
        ".ai/rules/dependencies.md",
        ".ai/rules/git-and-pr.md",
        ".ai/rules/documentation.md",
        ".ai/rules/diagramming.md",
        ".ai/rules/delivery-traceability.md",
        ".ai/rules/seo-geo.md",
        ".ai/rules/visual-design-integrity.md",
        ".ai/rules/animation-integrity.md",
        ".ai/workflows/start-task.md",
        ".ai/workflows/repository-intelligence-workflow.md",
        ".ai/workflows/plan-existing-system-change.md",
        ".ai/workflows/implement-feature.md",
        ".ai/workflows/fix-bug.md",
        ".ai/workflows/review-pr.md",
        ".ai/workflows/investigate-incident.md",
        ".ai/workflows/database-change.md",
        ".ai/workflows/create-design-document.md",
        ".ai/workflows/prepare-pr-or-mr.md",
        ".ai/workflows/synchronize-work-item.md",
        ".ai/workflows/prepare-jira-completion-package.md",
        ".ai/workflows/build-public-website.md",
        ".ai/prompts/task-contract.md",
        ".ai/prompts/existing-system-change-request.md",
        ".ai/prompts/plan-approval-response.md",
        ".ai/prompts/bug-report.md",
        ".ai/prompts/feature-request.md",
        ".ai/prompts/pr-review.md",
        ".ai/prompts/incident-investigation.md",
        ".ai/prompts/prepare-pr-or-mr.md",
        ".ai/prompts/prepare-jira-completion.md",
        ".ai/templates/jira-completion-comment.md",
        ".ai/templates/repository-intelligence-brief.md",
        ".ai/templates/change-impact-plan.md",
        ".ai/templates/implementation-approval-record.md",
        ".ai/templates/code-quality-review.md",
        ".ai/templates/memory-entry.yaml",
        ".ai/templates/demo-deck.yaml",
        ".ai/templates/demo-evidence-workbook.yaml",
        ".ai/templates/screenshot-placeholders.md",
        ".ai/templates/seo-geo-review.md",
        ".ai/templates/design-brief.md",
        ".ai/templates/design-direction.md",
        ".ai/templates/visual-design-review.md",
        ".ai/templates/ui-state-inventory.md",
        ".ai/templates/motion-brief.md",
        ".ai/templates/motion-contract.md",
        ".ai/templates/animation-inventory.md",
        ".ai/templates/animation-review.md",
        ".ai/guards/policy.yaml",
        ".ai/guards/repository-intelligence-gate.yaml",
        ".ai/guards/implementation-approval-gate.yaml",
        ".ai/guards/code-quality-profile-gate.yaml",
        ".ai/guards/memory-governance.yaml",
        ".ai/guards/forbidden-paths.yaml",
        ".ai/guards/dependency-policy.yaml",
        ".ai/guards/sensitive-data-policy.yaml",
        ".ai/guards/change-risk-rules.yaml",
        ".ai/evals/README.md",
        ".ai/evals/scorecard.yaml",
        ".ai/evals/golden-cases.yaml",
        ".ai/scripts/sync_agent_assets.py",
        ".ai/scripts/validate_agent_config.py",
        ".ai/scripts/test_agent_policies.py",
        ".ai/scripts/generate_delivery_artifacts.py",
        ".ai/scripts/repository_intelligence_lib.py",
        ".ai/scripts/check-repository-intelligence.py",
        ".ai/scripts/install-repository-intelligence.py",
        ".ai/scripts/index-repository.py",
        ".ai/scripts/refresh-repository-index.py",
        ".ai/scripts/bootstrap-repository-intelligence.ps1",
        ".ai/scripts/bootstrap-repository-intelligence.sh",
        ".ai/docs/repository-intelligence-guide.md",
        ".ai/docs/agent-adapter-strategy.md",
        ".ai/quality-profiles/universal.yaml",
        ".ai/quality-profiles/go.yaml",
        ".ai/quality-profiles/java.yaml",
        ".ai/quality-profiles/python.yaml",
        ".ai/quality-profiles/typescript-javascript.yaml",
        ".ai/quality-profiles/frontend-html-css.yaml",
        ".ai/quality-profiles/web-app.yaml",
        ".ai/quality-profiles/seo-geo.yaml",
        ".ai/quality-profiles/visual-design.yaml",
        ".ai/quality-profiles/animation-motion.yaml",
        ".ai/quality-profiles/mobile-app.yaml",
        ".ai/quality-profiles/desktop-app.yaml",
        ".ai/quality-profiles/infrastructure.yaml",
        ".ai/quality-profiles/devops.yaml",
        ".ai/quality-profiles/api.yaml",
        ".ai/quality-profiles/database.yaml",
        ".ai/quality-profiles/concurrency.yaml",
        ".ai/quality-profiles/memory.yaml",
        ".mcp.json",
        ".codex/config.toml",
        ".codex/hooks.json",
        ".codex/rules/default.rules",
        ".claude/settings.json",
        ".claude/rules/shared-policy.md",
    ]


def parse_frontmatter(path: Path, errors: list[str]) -> dict[str, str]:
    text = read(path)
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        fail(errors, f"{path} missing YAML frontmatter")
        return {}
    try:
        end = lines[1:].index("---") + 1
    except ValueError:
        fail(errors, f"{path} frontmatter is not closed")
        return {}
    data: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        if ":" not in line:
            fail(errors, f"{path} has unsupported frontmatter line: {line}")
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def generated_content(source_rel: str, source_text: str) -> str:
    return f"{GENERATED_PREFIX}{source_rel}{GENERATED_SUFFIX}\n\n{source_text}"


def validate_required_files(root: Path, errors: list[str]) -> None:
    for rel in required_paths():
        if not (root / rel).exists():
            fail(errors, f"required path missing: {rel}")


def validate_root_links(root: Path, errors: list[str]) -> None:
    expected_links = [
        ".ai/guards/repository-intelligence-gate.yaml",
        ".ai/workflows/repository-intelligence-workflow.md",
        ".ai/PROMPTS.md",
        ".ai/core/required-workflow.md",
        ".ai/core/quality-gates.md",
        ".ai/core/code-quality-intelligence.md",
        ".ai/core/memory-policy.md",
        ".ai/core/risk-model.md",
        ".ai/core/output-contract.md",
        ".ai/guards/memory-governance.yaml",
        ".ai/guards/code-quality-profile-gate.yaml",
        ".ai/templates/memory-entry.yaml",
        ".ai/quality-profiles/",
        ".ai/context/repository-map.md",
        ".ai/rules/",
        ".ai/workflows/",
        ".ai/skills-src/",
    ]
    for root_file in ["AGENTS.md", "CLAUDE.md"]:
        text = read(root / root_file)
        for link in expected_links:
            if link not in text:
                fail(errors, f"{root_file} does not link to {link}")


def validate_skills(root: Path, errors: list[str]) -> None:
    src_root = root / ".ai" / "skills-src"
    names: set[str] = set()
    for skill_file in sorted(src_root.glob("*/SKILL.md")):
        data = parse_frontmatter(skill_file, errors)
        name = data.get("name", "")
        description = data.get("description", "")
        if not name:
            fail(errors, f"{skill_file} missing name")
        elif not NAME_RE.fullmatch(name):
            fail(errors, f"{skill_file} name must be lowercase hyphenated: {name}")
        elif name in names:
            fail(errors, f"duplicate skill name: {name}")
        names.add(name)
        if not description:
            fail(errors, f"{skill_file} missing description")
        if skill_file.parent.name != name:
            fail(errors, f"{skill_file} folder name must match frontmatter name {name}")

        source_rel = skill_file.relative_to(root).as_posix()
        expected = generated_content(source_rel, read(skill_file))
        for dest_root in [root / ".agents" / "skills", root / ".claude" / "skills"]:
            dest = dest_root / name / "SKILL.md"
            if not dest.exists():
                fail(errors, f"missing generated skill: {dest.relative_to(root)}")
            elif read(dest) != expected:
                fail(errors, f"generated skill drift: {dest.relative_to(root)}")


def validate_json_toml(root: Path, errors: list[str]) -> None:
    for json_file in [root / ".codex" / "hooks.json", root / ".claude" / "settings.json", root / ".mcp.json"]:
        try:
            json.loads(read(json_file))
        except Exception as exc:  # noqa: BLE001
            fail(errors, f"invalid JSON {json_file.relative_to(root)}: {exc}")

    toml_files = [root / ".codex" / "config.toml", *sorted((root / ".codex" / "agents").glob("*.toml"))]
    if tomllib is None:
        fail(errors, "Python 3.11+ tomllib is required to validate TOML files")
        return
    for toml_file in toml_files:
        try:
            tomllib.loads(read(toml_file))
        except Exception as exc:  # noqa: BLE001
            fail(errors, f"invalid TOML {toml_file.relative_to(root)}: {exc}")


def validate_manifest_paths(root: Path, errors: list[str]) -> None:
    manifest = read(root / ".ai" / "manifest.yaml")
    for rel in re.findall(r'"(\.ai/[^"]+)"', manifest):
        if any(ch in rel for ch in "*?"):
            continue
        if not (root / rel).exists():
            fail(errors, f"manifest references missing path: {rel}")


def validate_hooks(root: Path, errors: list[str]) -> None:
    hooks_file = root / ".codex" / "hooks.json"
    try:
        hooks = json.loads(read(hooks_file))
    except Exception:
        return
    commands: list[str] = []
    for groups in hooks.get("hooks", {}).values():
        for group in groups:
            for hook in group.get("hooks", []):
                command = hook.get("command", "")
                command_windows = hook.get("commandWindows", "")
                if command:
                    commands.append(command)
                if command_windows:
                    commands.append(command_windows)
    for command in commands:
        lowered = command.lower()
        if any(term in lowered for term in ["curl ", "wget ", "invoke-webrequest", "http://", "https://", "iex "]):
            fail(errors, f"hook command appears to use network or download execution: {command}")
        match = re.search(r"(\.ai[\\/ ]scripts[\\/][A-Za-z0-9_.-]+\.py)", command)
        if match:
            rel = match.group(1).replace(" ", "/").replace("\\", "/")
            if not (root / rel).exists():
                fail(errors, f"hook references missing script: {rel}")
    joined = "\n".join(commands)
    if "bootstrap-repository-intelligence" not in joined and "check-repository-intelligence" not in joined:
        fail(errors, "session hooks do not invoke the Repository Intelligence Gate")


def validate_delivery_templates(root: Path, errors: list[str]) -> None:
    template_expectations = {
        ".ai/templates/jira-completion-comment.md": ["Repository intelligence", "RCA", "Solution", "MR/PR", "Acceptance criteria", "Validation", "Docs/specs/diagrams", "Demo package", "Screenshot Placeholders"],
        ".ai/templates/change-impact-plan.md": [
            "Repository Intelligence Gate",
            "Indexed Facts",
            "Source-Code Verified Facts",
            "Problem Statement",
            "Current Behavior",
            "Change Area Boundary",
            "Impact Boundary",
            "Files Explicitly Approved For Change",
            "Areas Requiring Developer Review Before Touching",
            "Reason No Other Area Is Changed",
            "Approval Decision Requested",
        ],
        ".ai/templates/implementation-approval-record.md": ["Repository intelligence gate status", "Indexed analysis reviewed", "Approval status", "Approver", "Approved scope", "Delta approval required"],
        ".ai/templates/code-quality-review.md": ["Detected Stack", "Application/platform/domain", "Selected Quality Profiles", "Platform/domain profiles", "Quality Checks", "Language/version best practices", "Platform/domain best practices", "Database connection and transaction safety", "Concurrency/deadlock/leak risk", "Heap/resource memory risk", "Release/deployment safety"],
        ".ai/templates/memory-entry.yaml": ["title:", "category:", "scope:", "content:", "source:", "confidence:", "status:", "approver:", "review_date:"],
        ".ai/templates/repository-intelligence-brief.md": ["Gate Status", "Indexed Facts", "Source-Code Verified Facts", "Relevant Modules", "Entry Points And Call Paths", "Potential Impact Areas"],
        ".ai/templates/demo-deck.yaml": ["required_slides", "Manual screenshot placeholders"],
        ".ai/templates/demo-evidence-workbook.yaml": ["required_worksheets", "Screenshot Placeholders"],
        ".ai/templates/screenshot-placeholders.md": ["Placeholder ID", "Exact screen or evidence"],
        ".ai/templates/seo-geo-review.md": ["Mode And Scope", "Evidence And Limitations", "Discovery Contract", "Crawler And Usage Policy", "Structured Data Integrity", "Claims Boundary"],
        ".ai/templates/design-brief.md": ["Product Surface", "Audience And Outcome", "Content And Information Architecture", "Brand And Assets", "References", "Constraints", "Unknowns And Approval Needs"],
        ".ai/templates/design-direction.md": ["Design Read", "Direction Controls", "Principles And Anti-Goals", "Inspiration Boundary", "Design System", "Responsive Composition", "State Coverage", "Approval Boundary"],
        ".ai/templates/visual-design-review.md": ["Scope And Direction", "Evidence", "Findings", "System Consistency", "Interaction And State Coverage", "Responsive And Inclusive Design", "Performance And Delivery"],
        ".ai/templates/ui-state-inventory.md": ["Default", "Focus", "Loading", "Empty", "Error/recovery", "Success", "Responsive notes", "Evidence"],
        ".ai/templates/motion-brief.md": ["Surface And Context", "Animation Decision", "Interaction And Lifecycle", "Accessibility And Fallback", "Performance And Compatibility", "Scope And Approval"],
        ".ai/templates/motion-contract.md": ["Token or pattern", "Interrupt/cancel behavior", "Reduced motion", "Runtime Contract", "Accessibility And Static Equivalence", "Performance And Compatibility Budget"],
        ".ai/templates/animation-inventory.md": ["Trigger", "Purpose", "Frequency", "Interruptible", "Reduced motion", "Cleanup/lifecycle", "Evidence", "Action"],
        ".ai/templates/animation-review.md": ["Scope And Environment", "Evidence", "Findings", "Decision And Timing", "Interruptibility, Gesture, And Lifecycle", "Accessibility", "Performance And Compatibility"],
    }
    for rel, fragments in template_expectations.items():
        text = read(root / rel)
        for fragment in fragments:
            if fragment not in text:
                fail(errors, f"{rel} missing required section or fragment: {fragment}")

    policy_text = read(root / ".ai" / "guards" / "implementation-approval-gate.yaml")
    for fragment in ["fail-closed", "approval_evidence_required", "outside_approved_scope", "agent_self_authorization_allowed: false"]:
        if fragment not in policy_text:
            fail(errors, f"implementation approval gate missing: {fragment}")


def validate_team_ready_governance(root: Path, errors: list[str]) -> None:
    output_contract = read(root / ".ai" / "core" / "output-contract.md")
    for fragment in [
        "Summary",
        "Context reviewed",
        "Root cause / rationale",
        "Changes made",
        "Files changed",
        "Tests executed",
        "Validation results",
        "Compatibility impact",
        "Security and performance considerations",
        "Assumptions",
        "Remaining risks",
        "Memory candidates",
    ]:
        if fragment not in output_contract:
            fail(errors, f"output contract missing section: {fragment}")

    quality_gates = read(root / ".ai" / "core" / "quality-gates.md")
    for fragment in [
        "PASSED",
        "FAILED",
        "NOT_APPLICABLE",
        "NOT_RUN",
        "Compilation passed",
        "Unit tests passed",
        "Integration tests passed where applicable",
        "Static analysis passed",
        "Architecture checks passed",
        "Platform/domain quality profile selected",
        "Security checks passed",
        "Database migration validated",
        "API compatibility reviewed",
        "Observability impact reviewed",
        "Diff self-reviewed",
        "Evidence command/result",
    ]:
        if fragment not in quality_gates:
            fail(errors, f"quality gates missing required fragment: {fragment}")

    role_text = read(root / ".ai" / "context" / "agent-roles.md")
    guide_text = read(root / "AI_AGENT_TEAM_GUIDE.md")
    for role in ["Module Context Owner", "Memory Approver", "Skill Maintainer", "Quarterly Review"]:
        if role not in role_text:
            fail(errors, f"agent governance role missing: {role}")
        if role not in guide_text:
            fail(errors, f"team guide governance role missing: {role}")

    for fragment in [
        "Persona Composition Matrix",
        "Solution Architect",
        "Senior Backend Engineer",
        "Production SRE",
        "Security Engineer",
        "QA Lead",
        "Release Manager",
        "Tech Lead",
        "architecture-review",
        "performance-investigation",
        "observability-review",
        "security-review",
        "threat-model",
        "test-strategy",
        "release-readiness",
        "repository-health",
    ]:
        if fragment not in role_text:
            fail(errors, f"agent persona composition missing from role map: {fragment}")
        if fragment not in guide_text:
            fail(errors, f"agent persona composition missing from team guide: {fragment}")

    memory_policy = read(root / ".ai" / "core" / "memory-policy.md")
    for fragment in [
        "Allowed Memory Categories",
        "Denied Memory Categories",
        "Title",
        "Category",
        "Scope",
        "Content",
        "Source",
        "Confidence",
        "Status",
        "Approver",
        "Review date",
        "Current source code",
        "Tests",
        "Approved architecture docs",
        "Approved memory",
        "Historical discussion",
        "Agent inference",
        "at most 5 entries",
        "never more than 10 entries",
        "confidence `>= 0.8`",
    ]:
        if fragment not in memory_policy:
            fail(errors, f"memory policy missing required fragment: {fragment}")

    memory_guard = read(root / ".ai" / "guards" / "memory-governance.yaml")
    for fragment in [
        "default_retrieval: \"approved-only\"",
        "approval_required: true",
        "APPROVED",
        "PROPOSED",
        "STALE",
        "preferred_minimum: 0.8",
        "default_max_entries: 5",
        "absolute_max_entries: 10",
        "pii",
        "secrets",
        "production_customer_data",
        "cadence: \"quarterly\"",
    ]:
        if fragment not in memory_guard:
            fail(errors, f"memory governance guard missing required fragment: {fragment}")

    policy_text = read(root / ".ai" / "guards" / "policy.yaml")
    for fragment in ["quality_gates:", "memory_governance:", "max_entries_default: 5", "max_entries_absolute: 10"]:
        if fragment not in policy_text:
            fail(errors, f"policy guard missing required fragment: {fragment}")

    database_rules = read(root / ".ai" / "rules" / "database.md")
    for fragment in [
        "Do not call `repository.save()` inside large loops.",
        "batch update",
        "bulk persistence",
        "transaction size",
        "flush/clear behavior",
        "locking risk",
    ]:
        if fragment not in database_rules:
            fail(errors, f"database rules missing developer correction rule fragment: {fragment}")

    golden_cases = read(root / ".ai" / "evals" / "golden-cases.yaml")
    for case_id in [
        "repository-save-in-loop",
        "memory-candidate-approval",
        "memory-retrieval-bounded",
        "cross-area-change-without-approval",
    ]:
        if case_id not in golden_cases:
            fail(errors, f"golden cases missing required case: {case_id}")


def validate_code_quality_profiles(root: Path, errors: list[str]) -> None:
    core_text = read(root / ".ai" / "core" / "code-quality-intelligence.md")
    for fragment in [
        "language, version, framework",
        "selected quality profiles",
        "connection leaks",
        "deadlocks",
        "heap",
        "platform-aware",
        "platform/domain profiles",
    ]:
        if fragment not in core_text:
            fail(errors, f"code quality intelligence missing required fragment: {fragment}")

    guard_text = read(root / ".ai" / "guards" / "code-quality-profile-gate.yaml")
    for fragment in [
        "code-quality-profile-gate",
        "fail-closed",
        "select_platform_or_domain_profiles",
        "platform_domain_best_practices",
        "database_connection_leaks",
        "deadlock_risk",
        "heap_memory_leaks",
    ]:
        if fragment not in guard_text:
            fail(errors, f"code quality profile gate missing required fragment: {fragment}")

    profiles = {
        "universal.yaml": ["id: universal", "clean code", "resource cleanup"],
        "go.yaml": ["id: go", "go test ./...", "goroutine leaks are prevented"],
        "java.yaml": ["id: java", "repository.save", "thread pool", "heap retention"],
        "python.yaml": ["id: python", "pytest", "async", "session, transaction, cursor, and connection lifecycle"],
        "typescript-javascript.yaml": ["id: typescript-javascript", "tsc --noEmit", "event-loop", "Promise"],
        "frontend-html-css.yaml": ["id: frontend-html-css", "accessibility", "bundle"],
        "web-app.yaml": ["id: web-app", "Core Web Vitals", "XSS", "accessibility"],
        "mobile-app.yaml": ["id: mobile-app", "application lifecycle", "permissions", "battery"],
        "desktop-app.yaml": ["id: desktop-app", "code signing", "auto-update", "native resource cleanup"],
        "infrastructure.yaml": ["id: infrastructure", "terraform plan", "least privilege", "drift"],
        "devops.yaml": ["id: devops", "CI/CD", "release gates", "supply chain"],
        "api.yaml": ["id: api", "backward compatibility", "idempotency"],
        "database.yaml": ["id: database", "connection leaks prevented", "transaction"],
        "concurrency.yaml": ["id: concurrency", "deadlock", "task/thread/goroutine lifecycle"],
        "memory.yaml": ["id: memory", "heap retention", "resource cleanup"],
    }
    profile_root = root / ".ai" / "quality-profiles"
    for filename, fragments in profiles.items():
        path = profile_root / filename
        if not path.exists():
            fail(errors, f"quality profile missing: {path.relative_to(root)}")
            continue
        text = read(path)
        for fragment in fragments:
            if fragment not in text:
                fail(errors, f"{path.relative_to(root)} missing required fragment: {fragment}")


def validate_prompt_catalog(root: Path, errors: list[str]) -> None:
    catalog = read(root / ".ai" / "PROMPTS.md")
    for prompt_name in [
        "start-task",
        "plan-change",
        "implement-approved",
        "fix-bug",
        "code-quality-review",
        "review-pr",
        "investigate-incident",
        "prepare-handoff",
    ]:
        if f"## {prompt_name}" not in catalog:
            fail(errors, f"prompt catalog missing prompt: {prompt_name}")
        if f"`{prompt_name}`" not in catalog:
            fail(errors, f"prompt catalog missing prompt table entry: {prompt_name}")
    for fragment in [
        "npx --yes @hunpeolabs/ai-agent-kit@latest bootstrap --yes",
        "npx --yes @hunpeolabs/ai-agent-kit@latest prompts",
        "npx --yes @hunpeolabs/ai-agent-kit@latest prompt start-task",
        "Do not edit files yet",
        "quality gates",
        "code-quality-review",
        "selected `.ai/quality-profiles/`",
        "memory candidates",
    ]:
        if fragment not in catalog:
            fail(errors, f"prompt catalog missing required fragment: {fragment}")


def validate_agent_adapter_strategy(root: Path, errors: list[str]) -> None:
    strategy = read(root / ".ai" / "docs" / "agent-adapter-strategy.md")
    for fragment in [
        "Claude Code",
        "OpenAI Codex",
        "GitHub Copilot",
        "Cursor",
        "Windsurf",
        "Gemini CLI",
        "Amazon Q Developer",
        "JetBrains Junie",
        "Cline",
        "Devin",
        "Aider",
        "Continue",
        "Adapter Contract",
        "Route the agent to `.ai/`",
        "Keep bootstrap local-only",
    ]:
        if fragment not in strategy:
            fail(errors, f"agent adapter strategy missing required fragment: {fragment}")


def validate_repository_intelligence(root: Path, errors: list[str], quick: bool) -> None:
    guard_text = read(root / ".ai" / "guards" / "repository-intelligence-gate.yaml")
    for fragment in [
        "@colbymchenry/codegraph",
        "cocoindex-code[full]",
        ".git/**",
        "**/node_modules/**",
        "**/target/**",
        "**/.env",
        "**/*.pem",
        "**/*cvv*",
        "**/*pan*",
        "compare_index_metadata_to_current_git_commit",
        "run_codegraph_health_query",
        "run_cocoindex_health_query",
    ]:
        if fragment not in guard_text:
            fail(errors, f"repository intelligence gate missing: {fragment}")

    for root_file in ["AGENTS.md", "CLAUDE.md", "AI_AGENT_TEAM_GUIDE.md"]:
        text = read(root / root_file)
        for fragment in ["Repository Intelligence Gate", "CodeGraph", "CocoIndex"]:
            if fragment not in text:
                fail(errors, f"{root_file} missing repository intelligence fragment: {fragment}")

    role_text = read(root / ".ai" / "context" / "agent-roles.md")
    required_roles = [
        "Team Lead Orchestrator",
        "Domain Analyst",
        "Impact Explorer",
        "Solution Architect",
        "Senior Backend Engineer",
        "Production SRE",
        "Security Engineer",
        "Tech Lead",
        "Implementation Engineer",
        "Database/Data Engineer",
        "Integration Engineer",
        "UI/UX Lead",
        "QA Lead",
        "Security Reviewer",
        "SRE/Release Engineer",
        "Release Manager",
        "Documentation Delivery Agent",
        "Independent Code Reviewer",
        "Module Context Owner",
        "Memory Approver",
        "Skill Maintainer",
        "Quarterly Review",
    ]
    for role in required_roles:
        if role not in role_text:
            fail(errors, f"agent role map missing role: {role}")
    if "repository-intelligence" not in role_text:
        fail(errors, "agent role map does not reference repository-intelligence skill")

    for agent_file in [*sorted((root / ".codex" / "agents").glob("*.toml")), *sorted((root / ".claude" / "agents").glob("*.md"))]:
        text = read(agent_file)
        if "repository-intelligence" not in text:
            fail(errors, f"agent role does not reference repository-intelligence skill: {agent_file.relative_to(root)}")

    plan_text = read(root / ".ai" / "workflows" / "plan-existing-system-change.md")
    for fragment in ["Repository Intelligence Gate", "Query CodeGraph", "Query CocoIndex", "repository intelligence brief"]:
        if fragment not in plan_text:
            fail(errors, f"plan workflow missing indexed impact analysis fragment: {fragment}")

    implement_text = read(root / ".ai" / "workflows" / "implement-feature.md")
    for fragment in ["Run the Repository Intelligence Gate", "Verify explicit approval evidence", "refresh CodeGraph/CocoIndex indexes"]:
        if fragment not in implement_text:
            fail(errors, f"implementation workflow missing gate fragment: {fragment}")

    required_workflow = read(root / ".ai" / "core" / "required-workflow.md")
    for fragment in ["Run the Repository Intelligence Gate", "Query CodeGraph", "refresh CodeGraph/CocoIndex indexes"]:
        if fragment not in required_workflow:
            fail(errors, f"required workflow missing repository intelligence fragment: {fragment}")

    mcp_text = read(root / ".mcp.json")
    if "codegraph" not in mcp_text or "cocoindex-code" not in mcp_text:
        fail(errors, ".mcp.json must configure codegraph and cocoindex-code")

    if quick:
        return

    result = subprocess.run(
        [
            sys.executable,
            str(root / ".ai" / "scripts" / "check-repository-intelligence.py"),
            "--json",
        ],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        timeout=240,
    )
    if result.returncode != 0:
        fail(errors, f"Repository Intelligence Gate check failed: {result.stderr.strip() or result.stdout.strip()}")
        return
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        fail(errors, f"Repository Intelligence Gate JSON invalid: {exc}")
        return
    if not payload.get("ready"):
        fail(errors, "Repository Intelligence Gate is not READY")


def validate_delivery_artifact_generator(root: Path, errors: list[str]) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp) / "artifacts"
        result = subprocess.run(
            [
                sys.executable,
                str(root / ".ai" / "scripts" / "generate_delivery_artifacts.py"),
                "--jira-key",
                "DEMO-000",
                "--title",
                "Validation Artifact",
                "--output-dir",
                str(out_dir),
                "--json",
            ],
            cwd=root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode != 0:
            fail(errors, f"delivery artifact generator failed: {result.stderr.strip() or result.stdout.strip()}")
            return
        try:
            payload = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            fail(errors, f"delivery artifact generator did not emit JSON: {exc}")
            return
        required_keys = {"summary", "pptx", "xlsx", "screenshot_placeholders"}
        if set(payload) != required_keys:
            fail(errors, f"delivery artifact generator emitted wrong keys: {sorted(payload)}")
            return
        for label, artifact_path in payload.items():
            path = Path(artifact_path)
            if not path.exists() or path.stat().st_size == 0:
                fail(errors, f"generated {label} artifact missing or empty: {path}")

        summary_text = Path(payload["summary"]).read_text(encoding="utf-8")
        if "DEMO-000" not in summary_text or "Validation Artifact" not in summary_text or "SS-01" not in summary_text:
            fail(errors, "generated Jira summary missing key, title, or screenshot placeholder")

        with zipfile.ZipFile(payload["pptx"]) as deck:
            names = set(deck.namelist())
            for required in ["ppt/presentation.xml", "ppt/slides/slide1.xml", "ppt/slides/slide6.xml"]:
                if required not in names:
                    fail(errors, f"generated PPTX missing {required}")
            slide_text = deck.read("ppt/slides/slide1.xml").decode("utf-8", errors="replace")
            if "DEMO-000" not in slide_text or "Validation Artifact" not in slide_text:
                fail(errors, "generated PPTX missing Jira key or title")

        with zipfile.ZipFile(payload["xlsx"]) as book:
            names = set(book.namelist())
            for required in ["xl/workbook.xml", "xl/worksheets/sheet1.xml", "xl/worksheets/sheet5.xml"]:
                if required not in names:
                    fail(errors, f"generated XLSX missing {required}")
            sheet_text = book.read("xl/worksheets/sheet1.xml").decode("utf-8", errors="replace")
            if "DEMO-000" not in sheet_text or "Validation Artifact" not in sheet_text:
                fail(errors, "generated XLSX missing Jira key or title")


def validate_secret_like_values(root: Path, errors: list[str]) -> None:
    scan_roots = [
        root / "AGENTS.md",
        root / "CLAUDE.md",
        root / "AI_AGENT_TEAM_GUIDE.md",
        root / ".ai",
        root / ".agents",
        root / ".codex",
        root / ".claude",
    ]
    files: list[Path] = []
    for item in scan_roots:
        if item.is_file():
            files.append(item)
        elif item.is_dir():
            files.extend(path for path in item.rglob("*") if path.is_file())
    for path in files:
        text = read(path)
        if SECRET_VALUE_RE.search(text):
            fail(errors, f"secret-like value found in {path.relative_to(root)}")


def validate_instruction_budgets(root: Path, errors: list[str]) -> None:
    budgets = {"AGENTS.md": 32 * 1024, "CLAUDE.md": 32 * 1024}
    for rel, limit in budgets.items():
        size = (root / rel).stat().st_size
        if size > limit:
            fail(errors, f"{rel} exceeds {limit} byte budget: {size}")


def validate_codex_rules_available(root: Path, errors: list[str], quick: bool) -> None:
    rules = root / ".codex" / "rules" / "default.rules"
    text = read(rules)
    for required in ["prefix_rule(", "match = [", "not_match = [", "decision = \"forbidden\"", "decision = \"prompt\""]:
        if required not in text:
            fail(errors, f"Codex rules file missing expected syntax: {required}")
    if quick:
        return
    codex = shutil.which("codex")
    if not codex:
        print("codex CLI unavailable; static .rules checks used as documented fallback")
        return
    result = subprocess.run(
        [codex, "execpolicy", "check", "--rules", str(rules), "--", "git", "status"],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        fail(errors, f"codex execpolicy check failed: {result.stderr.strip() or result.stdout.strip()}")


def validate(quick: bool = False) -> int:
    root = repo_root()
    errors: list[str] = []
    validate_required_files(root, errors)
    validate_root_links(root, errors)
    validate_skills(root, errors)
    validate_json_toml(root, errors)
    validate_manifest_paths(root, errors)
    validate_hooks(root, errors)
    validate_delivery_templates(root, errors)
    validate_team_ready_governance(root, errors)
    validate_code_quality_profiles(root, errors)
    validate_prompt_catalog(root, errors)
    validate_agent_adapter_strategy(root, errors)
    validate_delivery_artifact_generator(root, errors)
    validate_repository_intelligence(root, errors, quick)
    validate_secret_like_values(root, errors)
    validate_instruction_budgets(root, errors)
    validate_codex_rules_available(root, errors, quick)

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("agent configuration validation passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quick", action="store_true", help="skip optional external CLI checks")
    args = parser.parse_args()
    return validate(quick=args.quick)


if __name__ == "__main__":
    raise SystemExit(main())
