import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { loadScaffoldFiles } from "./assets.mjs";
import { detectProfile } from "./detect.mjs";
import { createTransaction, rollback, writeConfigFile, writeTransactionReport } from "./file-ops.mjs";
import { getBranch, getCommit, getManagedDiff, getStatus, requireGitRoot, statusToObject } from "./git.mjs";
import { isApprovedConfigPath, isProtectedApplicationPath } from "./paths.mjs";
import { createOwnershipPlan, finalizeOwnership } from "./ownership.mjs";
import { createRunner } from "./runner.mjs";
import {
  gitignoreSection,
  managedSection,
  renderJiraTemplate,
  renderMergeRequestTemplate,
  renderProjectYaml
} from "./templates.mjs";
import { checkCodeGraph, checkCocoIndex, refreshIndexes } from "./tools.mjs";
import { getPackageVersion } from "./version.mjs";

const GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from ";
const GENERATED_SUFFIX = ". DO NOT EDIT. -->";

function transactionId(now = new Date()) {
  const stamp = now.toISOString().replace(/[-:]/g, "").replace(/\..+$/, "Z");
  return `${stamp}-${crypto.randomBytes(3).toString("hex")}`;
}

function syncSkills(root, transaction, dryRun, { includeClaude, includeCodex }) {
  const srcRoot = path.join(root, ".ai", "skills-src");
  if (!fs.existsSync(srcRoot) || dryRun) return;
  for (const entry of fs.readdirSync(srcRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const source = path.join(srcRoot, entry.name, "SKILL.md");
    if (!fs.existsSync(source)) continue;
    const text = fs.readFileSync(source, "utf8");
    const sourceRel = path.relative(root, source).replaceAll("\\", "/");
    const generated = `${GENERATED_PREFIX}${sourceRel}${GENERATED_SUFFIX}\n\n${text}`;
    if (includeCodex) {
      writeConfigFile(root, transaction, `.agents/skills/${entry.name}/SKILL.md`, generated, { generatedOnly: true });
    }
    if (includeClaude) {
      writeConfigFile(root, transaction, `.claude/skills/${entry.name}/SKILL.md`, generated, { generatedOnly: true });
    }
  }
}

function installationFiles({ includeClaude, includeCodex }) {
  const files = loadScaffoldFiles();
  for (const rel of [...files.keys()]) {
    if (rel.startsWith(".claude/skills/")) files.delete(rel);
  }
  if (!includeClaude) {
    for (const rel of [...files.keys()]) {
      if (rel.startsWith(".claude/") || rel === "CLAUDE.md") files.delete(rel);
    }
  }
  if (!includeCodex) {
    for (const rel of [...files.keys()]) {
      if (rel.startsWith(".codex/") || rel.startsWith(".agents/") || rel === "AGENTS.md") files.delete(rel);
    }
  }
  return files;
}

function validateNoApplicationChanges(root, initialStatus, finalStatus, transaction, detection) {
  const errors = [];
  for (const rel of transaction.touched) {
    if (!isApprovedConfigPath(rel)) errors.push(`Non-approved path touched: ${rel}`);
    if (isProtectedApplicationPath(rel, detection.protectedPaths)) errors.push(`Protected application path touched: ${rel}`);
  }
  for (const [rel] of finalStatus) {
    const existedBefore = initialStatus.has(rel);
    if (!existedBefore && !isApprovedConfigPath(rel)) {
      errors.push(`Unexpected new non-AI path: ${rel}`);
    }
  }
  return errors;
}

function renderSummary({
  alreadyCurrent,
  root,
  packageVersion,
  preset,
  includeClaude,
  includeCodex,
  detection,
  transaction,
  toolStatus,
  validationPassed
}) {
  const indexSummary = transaction.indexResults.join(" ") || "No index action recorded.";
  if (alreadyCurrent) {
    return `AI Agent Kit Bootstrap: ALREADY CURRENT

Claude: ${includeClaude ? "READY" : "NOT_INSTALLED"}
Codex: ${includeCodex ? "READY" : "NOT_INSTALLED"}
CodeGraph: ${toolStatus.codegraph}
CocoIndex: ${toolStatus.cocoindex}
Index refresh: ${indexSummary}
Validation: PASSED

No local files required updating.
No application source code was modified.
No Git operations were performed.`;
  }
  return `AI Agent Kit Bootstrap: SUCCESS

Repository: ${root}
Package version: ${packageVersion}
Preset: ${preset}
Detected profile: ${detection.profile}
Transaction: ${transaction.transactionId}
Backup location: ${path.relative(root, transaction.backupRoot).replaceAll("\\", "/")}

Claude: ${includeClaude ? "READY" : "NOT_INSTALLED"}
Codex: ${includeCodex ? "READY" : "NOT_INSTALLED"}
CodeGraph: ${toolStatus.codegraph}
CocoIndex: ${toolStatus.cocoindex}
Index refresh: ${indexSummary}
Validation: ${validationPassed ? "PASSED" : "BLOCKED"}

Files created:
${transaction.filesCreated.map((file) => `- ${file}`).join("\n") || "- None"}
Files updated:
${transaction.filesUpdated.map((file) => `- ${file}`).join("\n") || "- None"}
Files preserved:
${transaction.filesPreserved.map((file) => `- ${file}`).join("\n") || "- None"}
Conflicts:
${transaction.conflicts.map((item) => `- ${item}`).join("\n") || "- None"}

No application source code was modified.
No files were staged.
No commit was created.
No branch was created.
No changes were pushed.
No merge request was created.`;
}

function reviewCommands() {
  return `Developer review commands:

git status
git diff -- AGENTS.md CLAUDE.md AI_AGENT_TEAM_GUIDE.md .ai .agents .claude .codex .ai-agent-kit .mcp.json .gitignore

Recommended staging command:

git add AGENTS.md CLAUDE.md AI_AGENT_TEAM_GUIDE.md .ai .agents .claude .codex .ai-agent-kit .mcp.json .gitignore

Recommended commit message:

chore(ai): add AI agent operating system

Suggested MR title:

chore(ai): add AI agent operating system`;
}

function promptNextSteps() {
  return `Prompt quick start:

- Open .ai/PROMPTS.md
- Or list prompts: npx --yes @hunpeolabs/ai-agent-kit@latest prompts
- Or print one prompt: npx --yes @hunpeolabs/ai-agent-kit@latest prompt start-task

Recommended first prompt:

Use start-task for this request:
[paste your ticket or requirement]`;
}

export async function bootstrap(options, deps = {}) {
  const io = deps.io ?? console;
  const runner = deps.runner ?? createRunner();
  const packageVersion = deps.packageVersion ?? getPackageVersion();
  const preset = options.preset ?? "governed";
  const root = requireGitRoot(runner, path.resolve(options.target));
  const gitInfo = { branch: getBranch(runner, root), commit: getCommit(runner, root) };
  const initialStatus = getStatus(runner, root);
  const detection = detectProfile(root, options.profile);
  const txId = deps.transactionId ?? transactionId(deps.now ?? new Date());
  const transaction = createTransaction(
    root,
    txId,
    packageVersion,
    statusToObject(initialStatus),
    detection,
    gitInfo,
    { createDirectories: !options.dryRun }
  );
  const includeClaude = !options.codexOnly;
  const includeCodex = !options.claudeOnly;
  let finalToolStatus = { codegraph: "BLOCKED", cocoindex: "BLOCKED" };

  try {
    if (options.dryRun) {
      const planned = installationFiles({ includeClaude, includeCodex });
      io.log(`AI Agent Kit Bootstrap: DRY RUN

Repository: ${root}
Preset: ${preset}
Detected profile: ${detection.profile}
Planned file operations:
${[...planned.keys()].map((file) => `- ${file}`).join("\n")}
- AGENTS.md managed section
- CLAUDE.md managed section
- AI_AGENT_TEAM_GUIDE.md
- .gitignore managed section

No files were modified.
No tools were installed.
No indexes were built.
No Git operations were performed.`);
      return { status: "dry-run", root, detection, transaction };
    }

    const scaffoldFiles = installationFiles({ includeClaude, includeCodex });
    const ownershipPlan = createOwnershipPlan(scaffoldFiles, { includeClaude, includeCodex });
    for (const [rel, content] of scaffoldFiles) {
      if (rel === "AGENTS.md" || rel === "CLAUDE.md") continue;
      writeConfigFile(root, transaction, rel, content, { generatedOnly: true });
    }
    if (scaffoldFiles.has("AGENTS.md")) {
      writeConfigFile(root, transaction, "AGENTS.md", managedSection(scaffoldFiles.get("AGENTS.md")), { mode: "managed-section" });
    }
    if (scaffoldFiles.has("CLAUDE.md")) {
      writeConfigFile(root, transaction, "CLAUDE.md", managedSection(scaffoldFiles.get("CLAUDE.md")), { mode: "managed-section" });
    }
    writeConfigFile(root, transaction, ".gitignore", gitignoreSection(), { mode: "managed-section" });
    syncSkills(root, transaction, options.dryRun, { includeClaude, includeCodex });

    writeConfigFile(root, transaction, ".ai-agent-kit/project.yaml", renderProjectYaml({ detection }));

    let toolStatus = {
      codegraph: checkCodeGraph(runner, root),
      cocoindex: checkCocoIndex(runner, root)
    };
    transaction.toolInstallationResults.push(`CodeGraph initial: ${toolStatus.codegraph.status}`);
    transaction.toolInstallationResults.push(`CocoIndex initial: ${toolStatus.cocoindex.status}`);
    transaction.toolInstallationResults.push("Bootstrap never installs global tools. Use tools plan and tools install --apply.");
    transaction.indexResults.push(...refreshIndexes(runner, root, toolStatus, options.refreshIndexes));
    finalToolStatus = { codegraph: toolStatus.codegraph.status, cocoindex: toolStatus.cocoindex.status };

    const resultForTemplates = {
      filesCreated: transaction.filesCreated,
      filesUpdated: transaction.filesUpdated,
      filesPreserved: transaction.filesPreserved,
      conflicts: transaction.conflicts,
      toolStatus: finalToolStatus,
      validationResults: transaction.validationResults,
      backupLocation: path.relative(root, transaction.backupRoot).replaceAll("\\", "/")
    };
    writeConfigFile(root, transaction, ".ai-agent-kit/output/merge-request-description.md", renderMergeRequestTemplate({
      packageVersion,
      detection,
      result: resultForTemplates
    }));
    writeConfigFile(root, transaction, ".ai-agent-kit/output/jira-update.md", renderJiraTemplate({ result: resultForTemplates }));

    const installation = {
      package: "@hunpeolabs/ai-agent-kit",
      version: packageVersion,
      contractVersion: 2,
      preset,
      repositoryRoot: root,
      repositoryCommit: gitInfo.commit,
      profile: detection.profile,
      technologies: detection.technologies,
      detectedVersions: detection.versions,
      detectedManifests: detection.manifests,
      adapters: { claude: includeClaude, codex: includeCodex },
      localOnly: true,
      managedFiles: finalizeOwnership(root, ownershipPlan, packageVersion)
    };
    writeConfigFile(root, transaction, ".ai-agent-kit/installation.json", `${JSON.stringify(installation, null, 2)}\n`);

    if (deps.failStep === "after-write") {
      throw new Error("Injected bootstrap failure after write");
    }

    const finalStatus = getStatus(runner, root);
    const validationErrors = validateNoApplicationChanges(root, initialStatus, finalStatus, transaction, detection);
    if (transaction.conflicts.length) validationErrors.push(...transaction.conflicts);
    if (validationErrors.length) {
      throw new Error(`Bootstrap validation failed:\n${validationErrors.join("\n")}`);
    }
    transaction.validationResults.push("AI-agent setup validation passed.");
    transaction.validationResults.push("No application source code was modified.");
    transaction.validationResults.push("No forbidden Git operations were performed.");
    writeTransactionReport(transaction);

    const diff = getManagedDiff(runner, root);
    const alreadyCurrent = transaction.filesCreated.length === 0 && transaction.filesUpdated.length === 0;
    io.log(renderSummary({
      alreadyCurrent,
      root,
      packageVersion,
      preset,
      includeClaude,
      includeCodex,
      detection,
      transaction,
      toolStatus: finalToolStatus,
      validationPassed: true
    }));
    if (diff.stdout.trim()) {
      io.log("\nLocal Git diff:\n");
      io.log(diff.stdout);
    }
    io.log(`\n${promptNextSteps()}`);
    io.log(`\n${reviewCommands()}`);
    return { status: alreadyCurrent ? "already-current" : "success", root, detection, transaction, toolStatus: finalToolStatus };
  } catch (error) {
    if (!options.dryRun) {
      rollback(root, transaction);
      writeTransactionReport(transaction);
    }
    throw error;
  }
}
