import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import {
  ADAPTERS,
  ALL_SKILL_ROOTS,
  adapterFlags,
  adapterLabels,
  resolveAdapterIds,
  selectedSkillRoots,
  shouldIncludeScaffoldPath
} from "./adapters.mjs";
import { loadScaffoldFiles } from "./assets.mjs";
import { detectProfile } from "./detect.mjs";
import { createTransaction, rollback, writeConfigFile, writeTransactionReport } from "./file-ops.mjs";
import { getBranch, getCommit, getManagedDiff, getStatus, requireGitRoot, statusToObject } from "./git.mjs";
import { hasSymlinkComponent, isApprovedConfigPath, isProtectedApplicationPath } from "./paths.mjs";
import { createOwnershipPlan, finalizeOwnership, ownedContent } from "./ownership.mjs";
import { createRunner } from "./runner.mjs";
import {
  gitignoreSection,
  managedSection,
  renderJiraTemplate,
  renderMergeRequestTemplate,
  renderProjectYaml
} from "./templates.mjs";
import { checkCodeGraph, checkCocoIndex, refreshIndexes } from "./tools.mjs";
import { getPackageVersion } from "./version.mjs";

const GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from ";
const GENERATED_SUFFIX = ". DO NOT EDIT. -->";
const MAX_SKILL_RESOURCE_FILES = 512;
const MAX_SKILL_RESOURCE_BYTES = 2 * 1024 * 1024;
const MAX_SKILL_TOTAL_BYTES = 16 * 1024 * 1024;

function transactionId(now = new Date()) {
  const stamp = now.toISOString().replace(/[-:]/g, "").replace(/\..+$/, "Z");
  return `${stamp}-${crypto.randomBytes(3).toString("hex")}`;
}

function canonicalSkillFiles(root, skillRoot) {
  const skillRootRel = path.relative(root, skillRoot).replaceAll("\\", "/");
  if (hasSymlinkComponent(root, skillRootRel)) {
    throw new Error(`Bootstrap refuses to read a symbolic link in canonical skill resources: ${skillRootRel}`);
  }
  const resolvedSkillRoot = fs.realpathSync(skillRoot);
  const files = [];
  let totalBytes = 0;

  const visit = (directory) => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
      const source = path.join(directory, entry.name);
      const sourceRel = path.relative(root, source).replaceAll("\\", "/");
      if (entry.isSymbolicLink() || hasSymlinkComponent(root, sourceRel)) {
        throw new Error(`Bootstrap refuses to read a symbolic link in canonical skill resources: ${sourceRel}`);
      }
      if (entry.isDirectory()) {
        visit(source);
        continue;
      }
      if (!entry.isFile()) {
        throw new Error(`Bootstrap refuses unsupported canonical skill resource type: ${sourceRel}`);
      }
      const resolvedSource = fs.realpathSync(source);
      const resolvedRel = path.relative(resolvedSkillRoot, resolvedSource);
      if (resolvedRel === ".." || resolvedRel.startsWith(`..${path.sep}`) || path.isAbsolute(resolvedRel)) {
        throw new Error(`Bootstrap refuses canonical skill resource outside its skill root: ${sourceRel}`);
      }
      const bytes = fs.lstatSync(source).size;
      if (bytes > MAX_SKILL_RESOURCE_BYTES) {
        throw new Error(`Canonical skill resource exceeds ${MAX_SKILL_RESOURCE_BYTES} byte limit: ${sourceRel}`);
      }
      files.push(source);
      totalBytes += bytes;
      if (files.length > MAX_SKILL_RESOURCE_FILES) {
        throw new Error(`Canonical skill exceeds ${MAX_SKILL_RESOURCE_FILES} resource limit: ${skillRootRel}`);
      }
      if (totalBytes > MAX_SKILL_TOTAL_BYTES) {
        throw new Error(`Canonical skill exceeds ${MAX_SKILL_TOTAL_BYTES} total byte limit: ${skillRootRel}`);
      }
    }
  };

  visit(skillRoot);
  return files;
}

function syncSkills(root, transaction, dryRun, selectedAdapters) {
  const srcRoot = path.join(root, ".ai", "skills-src");
  if (!fs.existsSync(srcRoot) || dryRun) return;
  const destinations = selectedSkillRoots(selectedAdapters);
  for (const entry of fs.readdirSync(srcRoot, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
    if (entry.isSymbolicLink()) {
      const sourceRel = path.relative(root, path.join(srcRoot, entry.name)).replaceAll("\\", "/");
      throw new Error(`Bootstrap refuses to read a symbolic link in canonical skill resources: ${sourceRel}`);
    }
    if (!entry.isDirectory()) continue;
    const skillRoot = path.join(srcRoot, entry.name);
    if (!fs.existsSync(path.join(skillRoot, "SKILL.md"))) continue;
    for (const source of canonicalSkillFiles(root, skillRoot)) {
      const text = fs.readFileSync(source, "utf8");
      const sourceRel = path.relative(root, source).replaceAll("\\", "/");
      const resourceRel = path.relative(skillRoot, source).replaceAll("\\", "/");
      const generated = `${GENERATED_PREFIX}${sourceRel}${GENERATED_SUFFIX}\n\n${text}`;
      for (const destination of destinations) {
        writeConfigFile(root, transaction, `${destination}/${entry.name}/${resourceRel}`, generated, { generatedOnly: true });
      }
    }
  }
}

function installationFiles(selectedAdapters) {
  const files = loadScaffoldFiles();
  for (const rel of [...files.keys()]) {
    if (ALL_SKILL_ROOTS.some((root) => rel.startsWith(`${root}/`))) {
      files.delete(rel);
      continue;
    }
    if (!shouldIncludeScaffoldPath(rel, selectedAdapters)) files.delete(rel);
  }
  return files;
}

function validateNoApplicationChanges(root, initialStatus, finalStatus, transaction, detection) {
  const errors = [];
  for (const rel of transaction.touched) {
    if (!isApprovedConfigPath(rel)) errors.push(`Non-approved path touched: ${rel}`);
    if (isProtectedApplicationPath(rel, detection.protectedPaths)) errors.push(`Protected application path touched: ${rel}`);
  }
  for (const [rel] of finalStatus) {
    const existedBefore = initialStatus.has(rel);
    if (!existedBefore && !isApprovedConfigPath(rel)) {
      errors.push(`Unexpected new non-AI path: ${rel}`);
    }
  }
  return errors;
}

function renderSummary({
  alreadyCurrent,
  root,
  packageVersion,
  preset,
  selectedAdapters,
  detection,
  transaction,
  toolStatus,
  validationPassed
}) {
  const indexSummary = transaction.indexResults.join(" ") || "No index action recorded.";
  const adapterSummary = selectedAdapters.map((id) => `${ADAPTERS[id].label}: READY`).join("\n");
  if (alreadyCurrent) {
    return `AI Agent Kit Bootstrap: ALREADY CURRENT

${adapterSummary}
CodeGraph: ${toolStatus.codegraph}
CocoIndex: ${toolStatus.cocoindex}
Index refresh: ${indexSummary}
Validation: PASSED

No local files required updating.
No application source code was modified.
No Git operations were performed.`;
  }
  return `AI Agent Kit Bootstrap: SUCCESS

Repository: ${root}
Package version: ${packageVersion}
Preset: ${preset}
Detected profile: ${detection.profile}
Transaction: ${transaction.transactionId}
Backup location: ${path.relative(root, transaction.backupRoot).replaceAll("\\", "/")}

${adapterSummary}
CodeGraph: ${toolStatus.codegraph}
CocoIndex: ${toolStatus.cocoindex}
Index refresh: ${indexSummary}
Validation: ${validationPassed ? "PASSED" : "BLOCKED"}

Files created:
${transaction.filesCreated.map((file) => `- ${file}`).join("\n") || "- None"}
Files updated:
${transaction.filesUpdated.map((file) => `- ${file}`).join("\n") || "- None"}
Files preserved:
${transaction.filesPreserved.map((file) => `- ${file}`).join("\n") || "- None"}
Conflicts:
${transaction.conflicts.map((item) => `- ${item}`).join("\n") || "- None"}

No application source code was modified.
No files were staged.
No commit was created.
No branch was created.
No changes were pushed.
No merge request was created.`;
}

function reviewCommands() {
  return `Developer review commands:

git status
git diff -- AGENTS.md CLAUDE.md GEMINI.md CONVENTIONS.md .aider.conf.yml AI_AGENT_TEAM_GUIDE.md .ai .agents .claude .codex .github .cursor .windsurf .amazonq .junie .cline .clinerules .continue .ai-agent-kit .mcp.json .gitignore

Recommended staging command:

git add AGENTS.md CLAUDE.md GEMINI.md CONVENTIONS.md .aider.conf.yml AI_AGENT_TEAM_GUIDE.md .ai .agents .claude .codex .github .cursor .windsurf .amazonq .junie .cline .clinerules .continue .ai-agent-kit .mcp.json .gitignore

Recommended commit message:

chore(ai): add AI agent operating system

Suggested MR title:

chore(ai): add AI agent operating system`;
}

function promptNextSteps() {
  return `Prompt quick start:

- Open .ai/PROMPTS.md
- Or list prompts: npx --yes @hunpeolabs/ai-agent-kit@latest prompts
- Or print one prompt: npx --yes @hunpeolabs/ai-agent-kit@latest prompt start-task

No skill or version prefix is required. Describe the request naturally. The
Conversation Entry Gate routes a raw product idea to Product Genesis, resumes a
single active Product Workspace, or starts the existing-system workflow.

Example raw idea:

Mình muốn làm một ứng dụng giúp các salon giảm khách bỏ hẹn.

Example existing-system task:

[paste your ticket or requirement]`;
}

export async function bootstrap(options, deps = {}) {
  const io = deps.io ?? console;
  const runner = deps.runner ?? createRunner();
  const packageVersion = deps.packageVersion ?? getPackageVersion();
  const preset = options.preset ?? "governed";
  const root = requireGitRoot(runner, path.resolve(options.target));
  const gitInfo = { branch: getBranch(runner, root), commit: getCommit(runner, root) };
  const initialStatus = getStatus(runner, root);
  const detection = detectProfile(root, options.profile);
  const selectedAdapters = resolveAdapterIds(options);
  const txId = deps.transactionId ?? transactionId(deps.now ?? new Date());
  const transaction = createTransaction(
    root,
    txId,
    packageVersion,
    statusToObject(initialStatus),
    detection,
    gitInfo,
    { createDirectories: !options.dryRun }
  );
  let finalToolStatus = { codegraph: "BLOCKED", cocoindex: "BLOCKED" };

  try {
    if (options.dryRun) {
      const planned = installationFiles(selectedAdapters);
      io.log(`AI Agent Kit Bootstrap: DRY RUN

Repository: ${root}
Preset: ${preset}
Detected profile: ${detection.profile}
Selected adapters: ${adapterLabels(selectedAdapters).join(", ")}
Planned file operations:
${[...planned.keys()].map((file) => `- ${file}`).join("\n")}
- Selected root instruction files use managed sections
- AI_AGENT_TEAM_GUIDE.md
- .gitignore managed section

No files were modified.
No tools were installed.
No indexes were built.
No Git operations were performed.`);
      return { status: "dry-run", root, detection, transaction };
    }

    const scaffoldFiles = installationFiles(selectedAdapters);
    const ownershipPlan = createOwnershipPlan(scaffoldFiles, { selectedAdapters });
    for (const [rel, content] of scaffoldFiles) {
      if (["AGENTS.md", "CLAUDE.md", "GEMINI.md", "CONVENTIONS.md"].includes(rel)) continue;
      writeConfigFile(root, transaction, rel, content, { generatedOnly: true });
    }
    for (const rel of ["AGENTS.md", "CLAUDE.md", "GEMINI.md", "CONVENTIONS.md"]) {
      if (scaffoldFiles.has(rel)) {
        writeConfigFile(root, transaction, rel, managedSection(scaffoldFiles.get(rel)), { mode: "managed-section" });
      }
    }
    writeConfigFile(root, transaction, ".gitignore", gitignoreSection(), { mode: "managed-section" });
    syncSkills(root, transaction, options.dryRun, selectedAdapters);

    writeConfigFile(root, transaction, ".ai-agent-kit/project.yaml", renderProjectYaml({ detection }));

    let toolStatus = {
      codegraph: checkCodeGraph(runner, root),
      cocoindex: checkCocoIndex(runner, root)
    };
    transaction.toolInstallationResults.push(`CodeGraph initial: ${toolStatus.codegraph.status}`);
    transaction.toolInstallationResults.push(`CocoIndex initial: ${toolStatus.cocoindex.status}`);
    transaction.toolInstallationResults.push("Bootstrap never installs global tools. Use tools plan and tools install --apply.");
    transaction.indexResults.push(...refreshIndexes(runner, root, toolStatus, options.refreshIndexes));
    finalToolStatus = { codegraph: toolStatus.codegraph.status, cocoindex: toolStatus.cocoindex.status };

    const resultForTemplates = {
      filesCreated: transaction.filesCreated,
      filesUpdated: transaction.filesUpdated,
      filesPreserved: transaction.filesPreserved,
      conflicts: transaction.conflicts,
      toolStatus: finalToolStatus,
      validationResults: transaction.validationResults,
      backupLocation: path.relative(root, transaction.backupRoot).replaceAll("\\", "/")
    };
    writeConfigFile(root, transaction, ".ai-agent-kit/output/merge-request-description.md", renderMergeRequestTemplate({
      packageVersion,
      detection,
      result: resultForTemplates
    }));
    writeConfigFile(root, transaction, ".ai-agent-kit/output/jira-update.md", renderJiraTemplate({ result: resultForTemplates }));

    const managedFiles = finalizeOwnership(root, ownershipPlan, packageVersion).map((entry) => {
      const baseSnapshot = `.ai-agent-kit/baselines/${packageVersion}/${entry.path}`;
      const content = ownedContent(root, entry);
      writeConfigFile(root, transaction, baseSnapshot, content);
      return { ...entry, baseSnapshot, baseSha256: crypto.createHash("sha256").update(content, "utf8").digest("hex") };
    });
    const installation = {
      package: "@hunpeolabs/ai-agent-kit",
      version: packageVersion,
      contractVersion: 3,
      preset,
      repositoryRoot: root,
      repositoryCommit: gitInfo.commit,
      profile: detection.profile,
      technologies: detection.technologies,
      detectedVersions: detection.versions,
      detectedManifests: detection.manifests,
      adapters: adapterFlags(selectedAdapters),
      localOnly: true,
      managedFiles
    };
    writeConfigFile(root, transaction, ".ai-agent-kit/installation.json", `${JSON.stringify(installation, null, 2)}\n`);

    if (deps.failStep === "after-write") {
      throw new Error("Injected bootstrap failure after write");
    }

    const finalStatus = getStatus(runner, root);
    const validationErrors = validateNoApplicationChanges(root, initialStatus, finalStatus, transaction, detection);
    if (transaction.conflicts.length) validationErrors.push(...transaction.conflicts);
    if (validationErrors.length) {
      throw new Error(`Bootstrap validation failed:\n${validationErrors.join("\n")}`);
    }
    transaction.validationResults.push("AI-agent setup validation passed.");
    transaction.validationResults.push("No application source code was modified.");
    transaction.validationResults.push("No forbidden Git operations were performed.");
    writeTransactionReport(transaction);

    const diff = getManagedDiff(runner, root);
    const alreadyCurrent = transaction.filesCreated.length === 0 && transaction.filesUpdated.length === 0;
    io.log(renderSummary({
      alreadyCurrent,
      root,
      packageVersion,
      preset,
      selectedAdapters,
      detection,
      transaction,
      toolStatus: finalToolStatus,
      validationPassed: true
    }));
    if (diff.stdout.trim()) {
      io.log("\nLocal Git diff:\n");
      io.log(diff.stdout);
    }
    io.log(`\n${promptNextSteps()}`);
    io.log(`\n${reviewCommands()}`);
    return { status: alreadyCurrent ? "already-current" : "success", root, detection, transaction, toolStatus: finalToolStatus };
  } catch (error) {
    if (!options.dryRun) {
      rollback(root, transaction);
      writeTransactionReport(transaction);
    }
    throw error;
  }
}
