import fs from "node:fs";
import path from "node:path";
import { isApprovedConfigPath, normalizeRelPath } from "./paths.mjs";
import { MANAGED_BEGIN, MANAGED_END } from "./templates.mjs";

export function ensureParent(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

export function readIfExists(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
}

export function mergeManagedSection(existing, section) {
  if (existing == null || existing.length === 0) return section;
  const begin = existing.indexOf(MANAGED_BEGIN);
  const end = existing.indexOf(MANAGED_END);
  if ((begin === -1) !== (end === -1)) {
    return { conflict: "managed section markers are incomplete" };
  }
  if (begin === -1) {
    const spacer = existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${spacer}${section}`;
  }
  const afterEnd = end + MANAGED_END.length;
  return `${existing.slice(0, begin)}${section.trimEnd()}${existing.slice(afterEnd)}`;
}

export function createTransaction(root, transactionId, packageVersion, initialStatus, detection, gitInfo, options = {}) {
  const txRoot = path.join(root, ".ai-agent-kit", "transactions", transactionId);
  const backupRoot = path.join(root, ".ai-agent-kit", "backups", transactionId);
  if (options.createDirectories !== false) {
    fs.mkdirSync(txRoot, { recursive: true });
    fs.mkdirSync(backupRoot, { recursive: true });
  }
  const state = {
    transactionId,
    packageVersion,
    repositoryRoot: root,
    repositoryCommit: gitInfo.commit,
    initialGitStatus: initialStatus,
    detectedProfile: detection,
    installationPlan: [],
    filesCreated: [],
    filesUpdated: [],
    filesPreserved: [],
    filesSkipped: [],
    conflicts: [],
    backups: [],
    toolInstallationResults: [],
    indexResults: [],
    validationResults: [],
    txRoot,
    backupRoot,
    touched: new Set()
  };
  return state;
}

export function writeTransactionReport(transaction, filename = "report.json") {
  const serializable = { ...transaction, touched: [...transaction.touched] };
  fs.writeFileSync(path.join(transaction.txRoot, filename), JSON.stringify(serializable, null, 2) + "\n");
}

function backupExisting(root, transaction, relPath) {
  const source = path.join(root, relPath);
  if (!fs.existsSync(source)) return null;
  const backup = path.join(transaction.backupRoot, relPath);
  ensureParent(backup);
  fs.copyFileSync(source, backup);
  transaction.backups.push({ relPath, backup: path.relative(root, backup).replaceAll("\\", "/") });
  return backup;
}

export function writeConfigFile(root, transaction, relPath, content, options = {}) {
  const rel = normalizeRelPath(relPath);
  if (!isApprovedConfigPath(rel)) {
    throw new Error(`Bootstrap attempted to modify a non-approved path: ${rel}`);
  }
  transaction.installationPlan.push({ relPath: rel, mode: options.mode ?? "replace" });
  if (options.dryRun) return { action: "planned" };

  const filePath = path.join(root, rel);
  const existing = readIfExists(filePath);
  let next = content;
  if (options.mode === "managed-section") {
    const merged = mergeManagedSection(existing, content);
    if (typeof merged === "object" && merged.conflict) {
      transaction.conflicts.push(`${rel}: ${merged.conflict}`);
      transaction.filesSkipped.push(rel);
      return { action: "conflict" };
    }
    next = merged;
  } else if (
    existing != null &&
    existing !== content &&
    options.generatedOnly &&
    !existing.includes("Generated by @hunpeolabs/ai-agent-kit") &&
    !existing.includes("GENERATED by .ai/scripts/sync_agent_assets.py from") &&
    !existing.includes("GENERATED from .ai/skills-src")
  ) {
    transaction.conflicts.push(`${rel}: existing non-generated file would be overwritten`);
    transaction.filesPreserved.push(rel);
    return { action: "preserved" };
  }

  if (existing === next) {
    transaction.filesPreserved.push(rel);
    return { action: "unchanged" };
  }

  if (existing != null) backupExisting(root, transaction, rel);
  ensureParent(filePath);
  fs.writeFileSync(filePath, next, "utf8");
  transaction.touched.add(rel);
  if (existing == null) transaction.filesCreated.push(rel);
  else transaction.filesUpdated.push(rel);
  return { action: existing == null ? "created" : "updated" };
}

export function rollback(root, transaction) {
  for (const rel of [...transaction.touched].reverse()) {
    const backup = transaction.backups.find((item) => item.relPath === rel);
    const target = path.join(root, rel);
    if (backup) {
      ensureParent(target);
      fs.copyFileSync(path.join(root, backup.backup), target);
    } else if (fs.existsSync(target)) {
      fs.rmSync(target, { force: true, recursive: true });
    }
  }
  writeTransactionReport(transaction, "rollback-report.json");
}
